require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'it']

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Rails/FilePath:
  Enabled: false
